"""Phase retrieval by nonlinear optimisation -- the problem, and its ground truth.

Follows Jurling & Fienup (2014), JOSA A 31(7) 1348, "Applications of algorithmic
differentiation to phase retrieval algorithms": estimate a wavefront by handing a
parametrised forward model to a quasi-Newton optimiser, rather than by iterating
Gerchberg-Saxton. Their argument is that the gradient is the whole cost story --
a P-parameter model costs P+1 forward evaluations per finite-difference gradient
and O(1) per analytic one -- and this board is built to measure exactly that
ratio on real optical-propagation codes.

    parameters   theta in R^P   Noll Zernikes 1..P, waves RMS, seeded
    forward      obstructed pupil -> OPD = sum(theta_i Z_i) -> phasor
                 -> propagate to focus -> I = |E|^2
    loss         L(theta) = mean( ((I(theta) - I_obs) / s)^2 ),  s = max(I_obs)
    solve        L-BFGS-B from theta = 0
    deliverable  theta_hat, and the wall time it took to get there

WHAT IS PINNED, AND WHY. Everything an optimiser could differ on lives in the
case file and is applied identically by `minimise` below: the truth
coefficients, the starting guess, ftol, gtol, the iteration cap and the L-BFGS
history length. A timing comparison between two codes that stopped on different
criteria is not a comparison, and the failure is silent -- both runs look fine
and one simply did less work.

THE BASIS IS SUPPLIED BY THE HARNESS, which is a deliberate exception to "let
each library do it its way" and the one place this board overrides idiom. Every
one of these codes ships Zernikes (poppy.zernike, prysm.polynomials,
hcipy.mode_basis, lentil.zernike, proper.prop_zernikes, dLux.ZernikeBasis) and
every one of them normalises differently -- over the circumscribed disk, over the
annulus, analytically, numerically. If each rendered its own, `theta` would mean
a different wavefront in each code, so the six optimisers would be descending six
different landscapes and their iteration counts would not be comparable. Pinning
the basis makes theta mean one thing. What each library is still charged for is
everything downstream of the OPD array -- rebuilding its optic, its wavefront,
re-applying its mask -- which is where the real per-call differences live.

THE OBSERVED PSF IS EACH CODE'S OWN, generated by its own forward model at the
truth coefficients, untimed, in build(). The alternative -- one harness-generated
measurement fitted by all six -- is more like real phase retrieval but makes the
board measure model error: PROPER reaches the focal plane by a near-field Fresnel
propagation through a lens and lands 7.5e-5 from an exact Fourier transform, so
it would grind against an irreducible residual that says nothing about how fast
its optimisation is. Self-consistent data gives every code a problem with the
same conditioning and a global minimum of exactly zero at the truth. The
cross-code check that this is not hiding a wrong forward model is kept, as a
separate untimed gate: `forward_accuracy` compares each code's observed PSF
against this module's reference.

PISTON IS IN THE PARAMETER VECTOR AND IS UNOBSERVABLE. Noll 1..11 is what "the
first 11 Zernikes, up to primary spherical" means, and Noll 1 is piston, which a
PSF cannot see: dL/dtheta_1 is identically zero -- measured 7.5e-20 through
JAX's reverse mode. So the retrieval leaves it wherever it started and the
coefficient error is reported both over all P modes and over the observable
P-1. That is a property of intensity-only phase retrieval, kept visible rather
than tidied away by dropping the mode.

THE TWIN AMBIGUITY, and the two things that were needed to defeat it. A
centro-symmetric pupil makes OPD phi(x) and -phi(-x) produce the identical PSF,
so a single in-focus image cannot separate them. Measured on a
centro-symmetric variant of this case, L-BFGS-B drives the loss from 1.5e-3 to
3.2e-9 and returns the exact twin -- every mode of odd radial order sign-flipped,
coefficient error 1.27. The optimiser is not at fault; the problem has two
equally good answers.

  1. The pupil is made non-centro-symmetric, by spider vanes that are half-rays
     rather than full diameters. The truth then becomes the unique global
     minimum: loss 0 at the truth against 1.1e-6 at the twin.
  2. The retrieval starts from a perturbed estimate of the truth rather than
     from zero. Step 1 alone is NOT enough, and the measurement that shows it is
     the reason this is written down: with a cold start the retrieval recovers
     the truth at N=64 and N=128 and falls into the twin at N=256, 512 and 1024,
     because 1.1e-6 of symmetry breaking is invisible from a starting loss of
     1.5e-3 and which basin the path enters is decided by details that move with
     the grid. Widening the vanes until it happens to work at every size was
     tried and rejected -- 0.05 D was robust across the scan and 0.10 D broke at
     N=64, which is fitting the telescope to the optimiser.

A perturbed start is also how phase retrieval is normally deployed: fine phasing
refines a coarse estimate rather than starting from no knowledge at all. It is
seeded, so every adapter starts from the identical guess. What it buys the board
beyond correctness is comparability -- the iteration count then holds at 21-23
across the whole scan, so the runtime curve isolates the cost of ONE forward
model instead of confounding it with an iteration count that wanders between
sizes and between codes.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Callable

import numpy as np

from .case import Case
from .grid import aperture_mask, focus_coords, pupil_coords, zernike_basis


@dataclass
class Outcome:
    """What one retrieval produced. Returned by every adapter's timed region."""

    theta: np.ndarray
    loss_initial: float
    loss_final: float
    n_iterations: int
    #: Forward-model evaluations. For a numerical-gradient run this includes the
    #: finite-difference probes, which is the entire point of the board.
    n_fev: int
    n_jev: int
    converged: bool
    message: str = ""
    optimizer: str = "scipy.optimize.minimize(method='L-BFGS-B')"

    def to_dict(self) -> dict:
        d = asdict(self)
        d["theta"] = [float(v) for v in np.asarray(self.theta).ravel()]
        return d


def retrieval_parameters(case: Case, centering="pixel"
                         ) -> tuple[list[int], np.ndarray, np.ndarray, np.ndarray]:
    """(noll_indices, theta_true, theta_initial, basis) for a retrieval case.

    Seeded, so every adapter retrieves the same wavefront from the same starting
    point. A gradient is point-valued and an optimisation path even more so:
    two codes started at different theta are not running the same benchmark.
    """
    r = case.retrieval
    if r is None:
        raise ValueError(f"case {case.id!r} has no retrieval block")
    if r.basis != "zernike_noll":
        raise ValueError(f"unsupported retrieval basis {r.basis!r}")

    noll = r.noll_indices
    rng = np.random.default_rng(r.seed)
    theta_true = rng.normal(0.0, r.truth_amplitude_waves_rms, size=r.count)
    if r.initial == "zeros":
        theta_init = np.zeros_like(theta_true)
    elif r.initial == "truth_perturbed":
        theta_init = theta_true + rng.normal(
            0.0, r.initial_perturbation * r.truth_amplitude_waves_rms, size=r.count)
    else:                                          # unreachable after validate()
        raise ValueError(f"unknown retrieval.initial {r.initial!r}")
    return noll, theta_true, theta_init, zernike_basis(case, noll, centering)


def twin_coefficients(case: Case, theta: np.ndarray) -> np.ndarray:
    """The coefficient vector of the wavefront -phi(-x), the twin of phi(x).

    Under inversion through the origin a Zernike of radial order n picks up
    (-1)^n, and the twin also negates the whole wavefront, so a coefficient
    transforms as c -> (-1)^(n+1) c: modes of even radial order (piston,
    defocus, astigmatism, spherical) flip sign and modes of odd order (tip,
    tilt, coma, trefoil) keep it.

    Used only to *diagnose* a retrieval that landed on the twin. A pupil that is
    not centro-symmetric -- which is what `spider_span: radius` buys this board
    -- makes the twin a strictly worse fit and the truth the unique global
    minimum, so this should never be the nearer of the two.
    """
    from .grid import noll_to_nm

    n = np.array([noll_to_nm(j)[0] for j in case.retrieval.noll_indices])
    return ((-1.0) ** (n + 1)) * np.asarray(theta, dtype=float)


def observable_slice(case: Case) -> slice:
    """The modes a PSF can actually constrain: everything but piston.

    Noll 1 contributes a constant phase, which factors out of |E|^2 exactly, so
    its gradient is zero and the optimiser never moves it.
    """
    r = case.retrieval
    return slice(1, None) if r.first_noll == 1 else slice(None)


# ------------------------------------------------------------------- forward --
def reference_psf(case: Case, theta: np.ndarray, centering="pixel") -> np.ndarray:
    """Intensity PSF from the harness's own matrix DFT, in float64.

    Independent of every adapter and of the numpy_baseline adapter, exactly like
    reference.reference_mft, and used for the same purpose: to answer "is this
    code modelling the telescope the case describes" separately from "how fast
    did it solve the inverse problem".
    """
    _, _, _, basis = retrieval_parameters(case, centering)
    return _psf(case, np.asarray(theta, dtype=float), basis,
                aperture_mask(case, centering), _kernel(case, centering))


def _kernel(case: Case, centering="pixel") -> np.ndarray:
    x = pupil_coords(case, centering)
    u = focus_coords(case, centering)
    return np.exp(-2j * np.pi * np.outer(u, x))


def _psf(case: Case, theta: np.ndarray, basis: np.ndarray, amp: np.ndarray,
         kx: np.ndarray) -> np.ndarray:
    opd = np.tensordot(theta, basis, axes=(0, 0))
    w = amp * np.exp(2j * np.pi * opd)
    e = (kx @ w) @ kx.T * (case.dx_pupil ** 2)
    return np.abs(e) ** 2


def compare_forward_model(psf: np.ndarray, case: Case, theta: np.ndarray,
                          centering="pixel"):
    """Gate a code's own PSF against the reference, allowing an OPD sign flip.

    Returns (Comparison, sign), where sign is "+" or "-" for the OPD convention
    the code was found to use.

    Testing both is not laxity. exp(+2i.pi.OPD) and exp(-2i.pi.OPD) are both in
    circulation and neither is wrong -- this repo already says so, and
    validate.compare fits the equivalent conjugation out on every propagation
    board. What is different here is that the quantity being compared is an
    INTENSITY, which cannot carry the evidence: squaring the modulus destroys
    the sign, so it has to be recovered by testing the hypothesis rather than
    read off. MEASURED: POPPY's PSF at +theta reproduces this module's reference
    at -theta to 3.4e-16, i.e. exactly, and its own board never noticed because
    a field comparison conjugates the difference away.

    The sign does not reach the coefficients a retrieval returns, which is why
    it is reported rather than corrected. Each code fits an observed PSF
    generated by its own forward model, so both conventions recover the same
    theta -- POPPY lands 1.1e-5 from the truth either way. It matters only to
    someone reading recovered wavefronts across codes, which is exactly the
    person who needs to be told.
    """
    from . import validate

    best = None
    for sign, label in ((1.0, "+"), (-1.0, "-")):
        cmp_ = validate.compare_psf(
            psf, reference_psf(case, sign * np.asarray(theta, dtype=float), centering),
            case, case.retrieval.max_forward_rel_l2,
            "internal_phase_retrieval_forward", quantity="psf_intensity")
        if best is None or cmp_.rel_l2 < best[0].rel_l2:
            best = (cmp_, label)
    return best


def loss_scale(psf_observed: np.ndarray) -> float:
    """The divisor that makes the loss dimensionless and code-independent.

    The peak of the observed PSF, so L is O(1) in the residual, exactly zero at
    the truth, and comparable between a POPPY that normalises to entrance flux
    and a prysm that carries dx^2. Without this a shared ftol/gtol would mean a
    different convergence in every code -- and would do so invisibly.
    """
    peak = float(np.max(np.asarray(psf_observed, dtype=float)))
    if not np.isfinite(peak) or peak <= 0.0:
        raise ValueError(
            f"observed PSF has non-positive peak {peak!r}; the forward model "
            f"returned no light, so the loss cannot be normalised")
    return peak


# ----------------------------------------------------------------- optimiser --
def lbfgsb_options(case: Case) -> dict:
    """scipy's option dict, from the case. Every adapter passes exactly this.

    `maxfun` is pinned rather than left at scipy's 15000 default so that it can
    never become the binding constraint on the numerical board without saying
    so: at P=11 a finite-difference gradient costs 12 evaluations, and a run
    that silently stopped on a function-count cap would look like a fast
    convergence instead of a truncated one. The factor of 4 leaves room for the
    line search on top of maxiter full gradients.
    """
    r = case.retrieval
    return {
        "maxiter": r.max_iterations,
        "maxfun": r.max_iterations * (r.count + 2) * 4,
        "maxcor": r.history_size,
        "ftol": r.ftol,
        "gtol": r.gtol,
    }


def minimise(fun: Callable, theta0: np.ndarray, case: Case,
             jac: bool = False) -> Outcome:
    """The single L-BFGS-B call every scipy-driven adapter makes.

    Centralised so that no adapter can quietly differ on a tolerance, a history
    length or an iteration cap. `jac=True` means `fun` returns (loss, gradient);
    `jac=False` means it returns the loss alone and scipy forms the gradient by
    two-point finite differences -- 12 forward models per gradient at P=11.

    The difference step is left at scipy's own default: an ABSOLUTE 1e-8
    (`_minimize_lbfgsb`'s `eps`, passed through as `ScalarFunction`'s abs_step),
    not a relative one. That is what a user gets without asking, it is identical
    for all four codes on the numerical board, and against coefficients of order
    5e-2 in a float64 loss it is comfortably above the roundoff floor -- which
    is why the case pins complex128, since at single precision this board would
    be measuring noise rather than a gradient.

    This is inside the timed region. `scipy.optimize.minimize` is imported at
    module scope by its callers rather than here so the import does not land in
    the clock.
    """
    from scipy.optimize import minimize as _minimize

    theta0 = np.asarray(theta0, dtype=float)
    res = _minimize(fun, theta0, jac=jac, method="L-BFGS-B",
                    options=lbfgsb_options(case))

    loss_final = float(res.fun)
    return Outcome(
        theta=np.asarray(res.x, dtype=float),
        loss_initial=float("nan"),        # filled by the caller, which has theta0
        loss_final=loss_final,
        n_iterations=int(res.nit),
        n_fev=int(res.nfev),
        n_jev=int(getattr(res, "njev", 0) or 0),
        converged=bool(res.success),
        message=str(res.message),
    )


def make_report(outcome: Outcome, loss_initial: float, case: Case,
                focal_points_computed: int, **extra: Any) -> dict:
    """The `retrieval` result block, spelled identically by every adapter.

    Seven adapters reporting "how many evaluations did that take" in seven
    shapes would make the report's cost-per-evaluation column a per-adapter
    guess, so the shape is fixed here.

    `focal_points_computed` is the one field an adapter cannot be trusted to
    omit, because it is what keeps this board from being read as a propagator
    ranking. A matrix DFT evaluates ONLY the focal samples the case asks for --
    4096 here, at every pupil size. An FFT-based code cannot: its focal sampling
    is set by the ratio of beam to grid, so reaching q=2 forces it to compute the
    entire (q x N_across)^2 plane and discard the rest. At N_p=1024 that is
    4194304 points against 4096, and 99.90% of PROPER's output is cropped away.

    Recording it makes the difference visible in the table and the figure
    caption. It is a capability difference, not an inefficiency -- and, measured,
    it is NOT what makes PROPER slow here: the extra points cost an FFT almost
    nothing (2.4x the MFT's arithmetic at N_p=1024, and less than it below
    N_p=256). See docs/phase_retrieval_board.md.
    """
    d = outcome.to_dict()
    d["loss_initial"] = float(loss_initial)
    d["loss_reduction"] = (float(loss_initial / outcome.loss_final)
                           if outcome.loss_final > 0 else float("inf"))
    d["focal_points_computed"] = int(focal_points_computed)
    d["focal_points_requested"] = int(case.n_focus) ** 2
    d.update(extra)
    return d


# ------------------------------------------------------------------ reference --
def reference_retrieval(case: Case, centering="pixel") -> Outcome:
    """Ground truth for the board: the same retrieval in plain float64 NumPy.

    Hand-written adjoint, so it is cheap enough to run as a gate, and written
    independently of every adapter -- a reference that shares code with the
    thing it validates is not a reference. Never timed.
    """
    _, theta_true, theta_init, basis = retrieval_parameters(case, centering)
    amp = aperture_mask(case, centering)
    kx = _kernel(case, centering)
    scale = case.dx_pupil ** 2

    observed = _psf(case, theta_true, basis, amp, kx)
    s = loss_scale(observed)

    def loss_and_grad(theta: np.ndarray):
        opd = np.tensordot(theta, basis, axes=(0, 0))
        w = amp * np.exp(2j * np.pi * opd)
        e = (kx @ w) @ kx.T * scale
        inten = np.abs(e) ** 2
        resid = (inten - observed) / s
        loss = float(np.mean(resid ** 2))
        # dL/dI, carrying the 1/s from the normalisation twice: once for the
        # residual and once for the intensity it is differentiated against.
        ibar = 2.0 * resid / (resid.size * s)
        ebar = ibar * np.conj(e)
        wbar = (kx.T @ ebar) @ kx * scale
        phsbar = -4.0 * np.pi * np.imag(wbar * w)
        return loss, np.tensordot(basis, phsbar, axes=([1, 2], [0, 1]))

    out = minimise(loss_and_grad, theta_init, case, jac=True)
    out.loss_initial = float(loss_and_grad(theta_init)[0])
    out.optimizer = "reference: numpy adjoint + scipy L-BFGS-B"
    return out
